export const reactConfig = {
  "react/jsx-no-comment-textnodes": "warn",
  "react/jsx-no-duplicate-props": "warn",
  "react/no-array-index-key": "warn",
  "react/no-clone-element": "warn",
  "react/no-direct-mutation-state": "error",
  "react/no-redundant-should-component-update": "error",
  "react/no-string-refs": "error",
  "react-dom/no-dangerously-set-innerhtml": "warn",
  "react-dom/no-dangerously-set-innerhtml-with-children": "error",
  "react-dom/no-find-dom-node": "error",
  "react-dom/no-flush-sync": "error",
  "react-dom/no-hydrate": "error",
  "react-dom/no-namespace": "error",
  "react-dom/no-render": "error",
  "react-dom/no-render-return-value": "error",
  "react-dom/no-script-url": "warn",
  "react-dom/no-unsafe-iframe-sandbox": "warn",
  "react-dom/no-use-form-state": "error",
  "react-dom/no-void-elements-with-children": "error",
  "react-hooks/rules-of-hooks": "error",
  "react-hooks/exhaustive-deps": "warn",
};
